[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.ruff]
fix = true
target-version = "py38"  # py27 still intended
line-length = 120

[tool.ruff.lint]
extend-select = ["E", "F"]

[tool.pytest.ini_options]
addopts = "-s"
